pipeline {
    agent any 
    stages {
        
        stage('Build') { 
            steps {
                sh 'npm install'
            }
        }
       stage ("sonarQube analysis"){
	    steps {
		withSonarQubeEnv('Jenkins-Sonar-Integration'){
			sh "npm install sonar-scanner"
			sh "npm run sonar"
			}
		    }
		  } 
        }
 }
