pipeline {
    agent any 
    stages {
        
        stage('Build') { 
            steps {
                sh 'npm install'
            }
        }
       stage ("sonarQube analysis"){
	    steps {
		withSonarQubeEnv('sonar'){
			sh "npm install sonar-scanner"
			sh "npm run sonar"
			}
		    }
		  }  
		}	   
        
    }
}
